FROM node:18-alpine3.16

RUN mkdir -m 775 -p /app

WORKDIR /app

COPY package.json package.json

COPY package-lock.json package-lock.json

RUN npm ci 

## env needed for: node path error prevention
ENV PATH=/usr/src/node_modules/.bin:$PATH

RUN npm i -g nodemon

RUN npm install

EXPOSE 4000

# execute this command to open terminal 
CMD [ "npm", "run", "dev" ]