version: "3.9"
services:
  onepiecedb:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - $TEST_DB_PORT:$TEST_DB_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $TEST_DB_PASS
      MYSQL_DATABASE: $TEST_DB_NAME
      MYSQL_TCP_PORT: $TEST_DB_PORT
    volumes:
      - onepiecedb-folder:/var/lib/mysql
  onepiece:
    container_name: onepiece
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: nodemon --watch index.js
    ports:
      - $APP_PORT:$APP_PORT
    links:
      - onepiecedb
    volumes:
      - ./:/app
      - node_modules:/app/node_modules # prevent binding of host node_modules
    env_file: .env
volumes:
  onepiecedb-folder: {}
  node_modules: {}
